<div>
    <h2>Bien! Hemos creado la siguiente alerta</h2>

    <br>
    <br>

    <div>
        <p>Desde: <strong><?=$result['from']?></strong></p>
        <p>Hasta: <strong><?=$result['to']?></strong></p>
        <p>Fecha: <strong><?=$result['date']?></strong></p>
    </div>

    <br><br>
    <div>
        <p>
            Cada día el robot comprobará si tu billete ya está disponible. Si es así, te avisamos, enviándote un
            email aquí: <?=$result['email']?>
        </p>
    </div>
</div>

