<div>
    <h2>Vaya! Parece que ya existen billetes disponibles para ese recorrido y fecha:</h2>

    <br>
    <br>

    <div>
        <p>Desde: <strong><?=$result['from']?></strong></p>
        <p>Hasta: <strong><?=$result['to']?></strong></p>
        <p>Fecha: <strong><?=$result['date']?></strong></p>
    </div>

    <br><br>
    <a target="_blank" href="http://www.renfe.com/">Ir a renfe</a>
</div>

